version: '3'

vars:
  PACKAGE_NAME: arlon-core

tasks:
  # ========================================
  # Core Library Specific Tasks
  # ========================================

  build:
    desc: Build the core library
    cmds:
      - cargo build

  build:release:
    desc: Build the core library in release mode
    cmds:
      - cargo build --release

  test:
    desc: Run all tests for core library
    cmds:
      - cargo test

  test:unit:
    desc: Run unit tests only
    cmds:
      - cargo test --lib

  test:integration:
    desc: Run integration tests only
    cmds:
      - cargo test --test '*'

  test:verbose:
    desc: Run tests with verbose output
    cmds:
      - cargo test -- --nocapture

  check:
    desc: Check for compilation errors
    cmds:
      - cargo check

  clippy:
    desc: Run clippy linter
    cmds:
      - cargo clippy -- -D warnings

  fmt:
    desc: Format code
    cmds:
      - cargo fmt

  fmt:check:
    desc: Check formatting
    cmds:
      - cargo fmt --check

  doc:
    desc: Generate documentation
    cmds:
      - cargo doc --no-deps

  doc:open:
    desc: Generate and open documentation
    cmds:
      - cargo doc --no-deps --open

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  publish:dry:
    desc: Dry-run publish to crates.io
    cmds:
      - cargo publish --dry-run

  bench:
    desc: Run benchmarks
    cmds:
      - cargo bench

  example:usage:
    desc: Show example usage of the core library
    cmds:
      - echo "Example usage in documentation and tests"
      - echo "Check tests/integration_tests.rs for usage examples"